/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface AdoptionInterface extends ethers.utils.Interface {
  functions: {
    "adopters(uint256)": FunctionFragment;
    "adopt(uint256)": FunctionFragment;
    "getAdopters()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "adopters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "adopt", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getAdopters",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "adopters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "adopt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAdopters",
    data: BytesLike
  ): Result;

  events: {};
}

export class Adoption extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: AdoptionInterface;

  functions: {
    adopters(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "adopters(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    adopt(
      petId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adopt(uint256)"(
      petId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getAdopters(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    "getAdopters()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;
  };

  adopters(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "adopters(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  adopt(
    petId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adopt(uint256)"(
    petId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getAdopters(overrides?: CallOverrides): Promise<string[]>;

  "getAdopters()"(overrides?: CallOverrides): Promise<string[]>;

  callStatic: {
    adopters(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "adopters(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    adopt(petId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "adopt(uint256)"(
      petId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAdopters(overrides?: CallOverrides): Promise<string[]>;

    "getAdopters()"(overrides?: CallOverrides): Promise<string[]>;
  };

  filters: {};

  estimateGas: {
    adopters(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "adopters(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    adopt(petId: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "adopt(uint256)"(
      petId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getAdopters(overrides?: CallOverrides): Promise<BigNumber>;

    "getAdopters()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    adopters(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "adopters(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    adopt(
      petId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adopt(uint256)"(
      petId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getAdopters(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAdopters()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
